### PR TITLE
Profile SQL fix & Defining datastore boundry

### PR DESCRIPTION
**Pull request by MobileDan**
The motivation for my changes is to get MicroMDM to a state where the datastore has a clearly defined boundary. I want the datastore implementation easily swapped with another and make it straightforward to create a new datastore.

The codebase had many “Store” interfaces defined which represented an abstract interface to the datastore. I made the use of these datastore interfaces more consistent in terms of use and naming. I tried to distinguish between the database implementation vs Store abstraction in names.

When using MySQL as the datastore, BoltDB was still used for a few entities. I made changes so this cannot happen - only the selected datastore implementation is initialized.

I encountered 3 entities not implemented in MySQL: User, Blueprint and SCEP Challenge. I called them out with a TODO comment and a log message.  Endpoints related to entities not implemented in MySQL do not response and will cause a 404 not found response code. I don’t plan on implementing these since I am not planning to use MySQL - my datastore will be a microservice.

I introduced a new enum field in server.Server struct named “Datastore” that indicates the datastore implementation. This is used instead of checking if the MySQL database is not equal to nil (c.MysqlDB != nil) to determine the datastore.

This is a transitional state. I want to phase out every case where there is and “if” statement that changes the datastore implementation embedded within the general source code. Instead the general source code should only interact with an abstraction of the datastore (the “Store” Interfaces).

### CODE REVIEW

**Comment by Lepidopteron** [comment]
> The codebase had many “Store” interfaces defined which represented an abstract interface to the datastore. I made the use of these datastore interfaces more consistent in terms of use and naming. I tried to distinguish between the database implementation vs Store abstraction in names.
> ...
> This is a transitional state. I want to phase out every case where there is and “if” statement that changes the datastore implementation embedded within the general source code. Instead the general source code should only interact with an abstraction of the datastore (the “Store” Interfaces).

Thank you Dan, this has been on my list for a while now.

&nbsp;
> Endpoints related to entities not implemented in MySQL do not response and will cause a 404 not found response code.

Hm, I think a 501 would have been more appropriate.
Nevertheless, this would break running solutions. As the fallback to the bolted in this case was not perfect, but at least it was working with temporary values.
I gotta have a look here to fix this.

&nbsp;
> I introduced a new enum field in server.Server struct named “Datastore” that indicates the datastore implementation. This is used instead of checking if the MySQL database is not equal to nil (c.MysqlDB != nil) to determine the datastore.`

Cool. I got a local branch where I provided a flag for psql/mysql/boltdb. This could be perfectly integrated to the enum.
As it is a wipe's branch, this is an information you can also forget about for now :-)

**Comment by MobileDan** [comment]
Thanks for your feedback Tobias.

I prefer your suggestion of returning 501 for endpoints that are not implemented. I implemented what was easiest which was not building the handler for endpoints that were not using MySQL. I figured this code would not be used by the larger community until every datastore was implemented in MySQL. Having the warnings might prompt someone to complete it sooner.

I can see that using BoltDB as the datastore for the few entities that are not implemented in MySQL is a good interim state. If so, I’d suggest being explicit about it by using a Bolt DB database with a different name than would be used when Bolt DB is the selected datastore. When BoltDB is the selected datastore, the BoltDB database is stored at /var/db/micromdm/micromdm.db. If MySQL is the selected datastore, the entities not yet implemented in MySQL could be stored in a BoltDB database at something like /var/db/micromdm/micromdm_mysql.db.

I should probably be using Docker for my development but have started by using my Mac as a host for development and testing. I switch between using BoltDB and MySQL. I could not figure out how to get the DEP token key out of BoltDB so I created a different DEP token for running MicroMDM with BoltDB vs MySQL. Therefore, data from MicroMDM running BoltDB and MicroMDM runningMySQL databases should not be intermixed. That is why I made sure to remove any cases where using MySQL saved data to BoltDB and that is why I suggest the alternate Bolt database with MySQL. I can imagine this could be confusing for others also.

If and when all entities are implemented in MySQL, the above two paragraphs are irrelevant. Before all entities are implemented in MySQL, I will go with your preference.

Do you know if anyone has integrated PostgreSQL or has a public, forked repository where its being worked on? If so I would like to see it. It has been talked about for years but when asked about in the #MicroMDM slack channel Victor said it is not ready. I am not interested in using MySQL or PostgreSQL. I am interested in making the datastore clearly defined and easy to add new implementations.

I will have more commits in the near future. In my local repository I merged the latest code from main with the only merge conflict in go.mod & go.sum. To resolve this, I took main’s version of these files. When I add more commits to this pull request, I believe the merged commits will be included.

I have used Git for a long time on projects where I have full write access to the remote but not much with open source development on GitHub. Please offer any suggestions for how I can use Git more effectively when collaborating with you.

Thank You

**Comment by MobileDan** [comment]
I've separated the creation of all datastore implementations into a new package named `datastore`. All the "`if` MySQL (setup MySQL datastore) `else` (setup Bolt datastore) references in `micromdm.serve` and `server.server` are gone.

`datastore.bolt` has the Bolt setup and `datastore.mysq`l has the MySQL setup. `datastore.schem`a holds the list of Store abstractions that must be implemented. To add a new datasource, you'd focus on the `datastore` package and would not need to edit code distributed in many places in `micromdm.serve` and `server.server`.

The entities that are not yet implemented in MySQL (User, Blueprint and SCEP Challenge) are stored in a BoltDB with a different name so it could not be intermixed with the Bolt datastore.

**Comment by MobileDan** [comment]
Hi Tobias,

When I compare /platform/queue/builtin/db.go to platform/queue/mysql/mysql.go there is a difference I want to ask you about. 

Starting at line 65 in db.go (the left side in the image below) db.go has this code

```
	if resp.EnrollmentID != nil {
		udid = *resp.EnrollmentID
	}
```

while mysql.go has this code

```
	err := dbWrapper.Store.UpdateCommandStatus(ctx, resp)
	if err != nil {
		return nil, err
	}
```

Should this be different?

I ask because this and a few other methods can be consolidated into a common queue service for all datastores other than this difference. Note: The struct `DBWrapper` will have it name changed, that is temporary.

image

Thank You

**Comment by MobileDan** [comment]
I've figured out part of the difference I asked about in the previous post... platform/queue/mysql/mysql.go is based off of /platform/queue/queue.go as it was around 1/23/19. There was a commit to queue.go  on June 29, 2019 at 5:36:13 PM CDT  [127955d] Support User Enrollment (#597) that must have been merged into  /platform/queue/builtin/db.go but not  platform/queue/mysql/mysql.go. *I will apply it to mysql.go.

I am still wondering about UpdateCommandStatus(). Maybe this is something that the Bolt datastore code should have? This is the latest diff...

image

**Comment by Lepidopteron** [comment]
ThanK you @MobileDan, yes the diff EnrollmentID & UserID is based on the state when there was no multi user support on iPads.

Regarding the updated command status.

I think the bolt db storage just attaches the commands to a new array, wherever the new command status matches.

In SQL I preferred another approach, where we would update the object and not the container of the object.
I think from a key value store logic (bolt) it makes sense to move the object to another array, whereas the relational database should rather update one single value of a row.

**Comment by MobileDan** [comment]
Thanks for that explanation @Lepidopteron.

**Comment by MobileDan** [comment]
Should the line of code that sets the sql_mode be followed by an error check?
```
	// Required for TIMESTAMP DEFAULT 0
	_,err := db.Exec(`SET sql_mode = '';`)
```

Like this
```
	// Required for TIMESTAMP DEFAULT 0
	_,err := db.Exec(`SET sql_mode = '';`)
	if err != nil {
		return err
	}
```

There are 7 occurrences of this and none of them have error checks. I thought this could be intentional or possibly due to copying code that had it missing.

**Comment by Lepidopteron** [comment]
> Should the line of code that sets the sql_mode be followed by an error check?
> 
> ```
> 	// Required for TIMESTAMP DEFAULT 0
> 	_,err := db.Exec(`SET sql_mode = '';`)
> ```
> 
> Like this
> 
> ```
> 	// Required for TIMESTAMP DEFAULT 0
> 	_,err := db.Exec(`SET sql_mode = '';`)
> 	if err != nil {
> 		return err
> 	}
> ```
> 
> There are 7 occurrences of this and none of them have error checks. I thought this could be intentional or possibly due to copying code that had it missing.

Thank you Dan, the check would be appreciated.

**Comment by MobileDan** [comment]
@Lepidopteron, I plan to delete my fork of this repository from my GitHub account so I can fork MicroMDM directly. Unfortunately, I cannot have a fork of MicroMDM directly and a fork of your fork of MicroMDM in the same GitHub account. 

I am not sure how these changes will affect this pull request. I am keeping the commits from this pull request in a branch in my repository rather than a pull request. You can look at the branch if interested.

I can submit more targeted pull requests against this repository in the future to address specific issues.

Your changes to incorporate MySQL helped me understand MicroMDM and incorporate a custom datastore - thank you.

**Comment by MobileDan** [comment]
I am closing this pull request. Please see my previous comment for more info. Thank you.

**Pull request closed without merging**
